### ISSUE TITLE
Codacy has rules which are not indicated as part of the repo using something like Eslint

### ISSUE THREAD

**Issue by damianpoole** [klayveR/poe-ninja-api-manager#2]
Should really setup Eslint/Editorconfig for this repo and have the rule-set based on Codacy.
Appreciate Eslint/Editorconfig and Codacy may be new to you, Codacy is to me at least 😄 .

**Comment by klayver** [comment]
Haven't worked with Eslint yet, I'll have to look into it. I removed Codacy, didn't use it anymore anyways :smile:
